#include <stdio.h>
#include <stdlib.h>

#include <sys/shm.h>
#include <sys/stat.h>

#include "shm.h"

/*
 * Create a shm instance with autogenerated id.
 */
shm *shm_create(size_t length)
{
	shm *shared;

	if (length == 0) {
		fprintf(stderr,
			"shm.c - shm_create() : Cannot allocate 0 bytes.\n");
		return NULL;
	}

	/* Creating new shm instance */
	shared = (shm *)malloc(sizeof(shm));
	if (shared == NULL) {
		fprintf(stderr,
			"shm.c - shm_create() : Computer refuses to give more memory.\n");
		return NULL;
	}

	/* Generating new ID */
	shared->id = shmget(IPC_PRIVATE, length,
			    IPC_CREAT | IPC_EXCL | S_IRUSR | S_IWUSR);
	if (shared->id == -1) {
		fprintf(stderr,
			"shm.c - shm_create() : invalid shared memory reference\n");
		return NULL;
	}

	shared->length = length;

	shared->data = shmat((int)shared->id, 0, 0);
	if (shared->data == NULL) {
		fprintf(stderr,
			"shm.c - shm_create() : Computer refuses to give more shared memory.\n");
		return NULL;
	}

	return shared;
}

/*
 * Delete given shm instance and frees the memory.
 */
void shm_delete(shm *shared)
{
	if (shared == NULL) {
		fprintf(stderr,
			"shm.c - shm_delete() : SHM instance is NULL.\n");
		return;
	}

	shmctl((int)shared->id, IPC_RMID, 0);
	shmdt(shared->data);
	free(shared);
}

/*
 * Create a shm instance that is attachable to a preallocated shm segment,
 * given proper id
 */
shm *shm_open(unsigned int id, size_t length)
{
	shm *shared;

	if (length == 0) {
		fprintf(stderr,
			"shm.c - shm_open() : Cannot allocate 0 bytes.\n");
		return NULL;
	}

	/* Creating new shm instance */
	shared = (shm *)malloc(sizeof(shm));
	if (shared == NULL) {
		fprintf(stderr,
			"shm.c - shm_open() : Computer refuses to give more memory.\n");
		return NULL;
	}

	shared->id = id;

	shared->length = length;

	/* Attach to existent shared memory instance */
	shared->data = shmat((int)shared->id, 0, 0);
	if (shared->data == NULL) {
		fprintf(stderr,
			"shm.c - shm_open() : Computer refuses to give more shared memory.\n");
		return NULL;
	}

	return shared;
}

/*
 * Remove shm instance without detaching it.
 */
void shm_close(shm *shared)
{
	if (shared == NULL) {
		fprintf(stderr,
			"shm.c - shm_close() : SHM instance is NULL.\n");
		return;
	}

	shmdt(shared->data);
	free(shared);
}

void *shm_read(shm *shared)
{
	if (shared == NULL) {
		fprintf(stderr, "shm.c - shm_read() : SHM instance is NULL.\n");
		return NULL;
	}

	return shared->data;
}

void shm_write(shm *shared, const char *data, size_t length)
{
	unsigned int u;

	if (shared == NULL) {
		fprintf(stderr,
			"shm.c - shm_write() : SHM instance is NULL.\n");
		return;
	}
	if (data == NULL) {
		fprintf(stderr, "shm.c - shm_write() : Given data is NULL.\n");
		return;
	}
	if (length > shared->length) {
		fprintf(stderr,
			"shm.c - shm_write() : Data given are greater than reserved memory.\n");
		return;
	}

	for (u = 0; u < (unsigned int)length; u++) {
		shared->data[u] = data[u];
	}
}
